### ISSUE TITLE
includeexpr doesn't handle .pm6

### ISSUE THREAD

**Issue by cfa** [vim-perl/vim-perl6#15]
# Description of issue

The current definition of `includeexpr` in ftplugin/perl6.vim expects file suffixes to end with `.pm`:

    setlocal includeexpr=substitute(substitute(v:fname,'::','/','g'),'$','.pm','')

Unfortunately, this means that `.pm6` files can't be opened with `gf`.

**Comment by hoelzro** [comment]
It looks like we'll actually need to use `suffixesadd` to support multiple suffixes for this.

**Comment by cfa** [comment]
Yeah, it looks like:

    setlocal includeexpr=substitute(v:fname,'::','/','g')
    setlocal suffixesadd=.pm6,.pm

might do the trick.

**Comment by cfa** [comment]
Yes, but there's one problem with the above: `gf` on identifier `Foo` with match files `Foo`, `Foo.pm6`, `Foo.pm` in that order (i.e., the empty suffix matches, which is a regression).

I'm not sure how to exclude `Foo` from the list of candidates; looking through the docs now.

**Comment by cfa** [comment]
Oh, my mistake—that's not actually a regression. Vim will only try `includeexpr` if the bare name doesn't match; the existing ftplugin already matches `Foo` before `Foo.pm`.

So, I think it's fine to push the change.

**Comment by hoelzro** [comment]
Thanks for the change @cfa!  I merged your PR - it's a good change, and we can always build on top of it.

**Comment by cfa** [comment]
Thanks @hoelzro.
